### ISSUE TITLE
path-style requests via proxy request is working...

### ISSUE THREAD

**Issue by tnatanael** [egorFiNE/node-aws-sign#10]
Hy! I am using this lib, and the part of documentation you say that:
 I.e. there is no support for path-style bucket access.

It's not right, i am using path-style requests to sign and proxy a request and i'ts working fine...
What is the point of this affirmation?

**Comment by egorFiNE** [comment]
Could you show me a test case? Perhaps my comment was an artifact from the past

**Comment by tnatanael** [comment]
Maybe, i don't have a test case, my application is just a proxy wrapper for a third party  s3 api, i am using lastest nodejs 11.1.0, Express, just creating client options from the request headers, applying the sign method and proxying to a minio.io server... it's working perfectly...

**Comment by egorFiNE** [comment]
Is this is still an issue? 

Please feel free to reopen this ticket if so.
