### ISSUE TITLE
The version bump to 0.2.1 breaks anything running node before 8

### ISSUE THREAD

**Issue by justin-summerlin** [egorFiNE/node-aws-sign#9]
There are a number of packages that depend on this one using a caret `^` version, which allows both minor and patch changes, and others which use `~` on the incorrectly published `0.2.0`, but this is a major change.

I'd recommend unpublishing `0.2.1` and publishing as `2.0.0` or whatever major version, or at least publishing as `0.3.0`.

**Comment by egorFiNE** [comment]
You are right. Not only that, turns out what a mess is the versioning of this package :( 

Published "classic" 0.5.0, then published ES6 1.0.0 and deprecated 0.2.1. 

Thank you.
